### ISSUE TITLE
Map embed doesn't work anymore

### ISSUE THREAD

**Issue by shannonturner** [shannonturner/seriously#1]
Need to recreate it using Google maps or something else since the Geojson.io embed isn't working: Refused to display 'http://bl.ocks.org/anonymous/raw/a82bb275ed9cc3d47652/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.ocks.org".

**Comment by orb16** [comment]
Probably related to this: https://groups.google.com/forum/#!topic/d3-js/xBC30357zak?

**Comment by shannonturner** [comment]
Oh yep, that would explain it, thanks!

Closing this issue since I ended up replacing the embed with a static image a while back.
